name: bmt
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.8.1
  - asn1crypto=1.3.0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.8
  - cudatoolkit=10.0.130
  - cymem=1.31.2
  - cytoolz=0.9.0.1
  - dill=0.2.9
  - future=0.17.1
  - idna=2.9
  - intel-openmp=2020.0=166
  - joblib=0.14.1=py_0
  - libffi=3.2.1
  - libprotobuf=3.11.4
  - markdown=3.2.1
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - msgpack-numpy=0.4.4.3
  - msgpack-python=0.5.6
  - murmurhash=0.28.0
  - ninja=1.9.0
  - numpy=1.15.4
  - numpy-base=1.15.4
  - openjdk=8.0.152
  - openssl=1.1.1g
  - pandas=0.24.2
  - pip=20.0.2
  - plac=0.9.6
  - preshed=1.0.1
  - protobuf=3.11.4
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7 
  - pytorch=1.2.0
  - pytz=2020.1
  - regex=2018.07.11
  - requests=2.23.0
  - scikit-learn=0.22.1
  - scipy=1.3.1
  - setuptools=46.1.3
  - six=1.14.0
  - spacy=2.0.12
  - sqlite=3.31.1
  - tensorboard=1.14.0
  - termcolor=1.1.0
  - thinc=6.10.3
  - tk=8.6.8
  - toolz=0.10.0
  - tqdm=4.46.0
  - ujson=2.0.3 
  - urllib3=1.25.8
  - werkzeug=1.0.1 
  - wheel=0.34.2 
  - wrapt=1.10.11 
  - xz=5.2.5 
  - zlib=1.2.11 
  - pip:
    - torchtext==0.3.1

